### ISSUE TITLE
implement load next level

### ISSUE THREAD

**Issue by AndrewDKahn** [CIS-SoftwareDesign-S21/pro-04-project-16x16#16]
Looks like loading levels is managed by the "GameplayScene.java" file on line 194 (full method lower in the code)

If we follow the trail there a little we should be able to figure out how to load multiple levels.

**Comment by ApophisUSA** [comment]
It looks like there is already some stub code and existing code around loading levels, it may be sufficient to create a queue that holds the levels in story mode, then when the door "triggers" the next level to load the next one in the queue.
